# Generated by Django 3.1.5 on 2021-04-03 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_time', models.TimeField()),
                ('feed_date', models.DateField(auto_now_add=True)),
                ('location', models.CharField(max_length=150)),
                ('food_type', models.CharField(max_length=200)),
                ('food_quantity', models.CharField(max_length=250)),
                ('number_of_ducks', models.IntegerField()),
            ],
        ),
    ]
