# Generated by Django 3.1.5 on 2021-04-05 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedlog',
            name='feed_date',
        ),
    ]
